name: Format code

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: poetry install

    - name: Organize Imports with isort
      run: poetry run isort --check-only EMFieldML

    - name: Lint with Black
      run: poetry run black --check EMFieldML

    - name: Lint with Ruff
      run: poetry run ruff check EMFieldML

    # MyPy temporarily disabled due to extensive type annotation issues (874 errors)
    # TODO: Re-enable after fixing type annotations across the codebase
    # - name: Type check with MyPy
    #   run: poetry run mypy EMFieldML
